<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MonitorShop.DataAccess\MonitorShop.DataAccess.csproj" />
    <ProjectReference Include="..\MonitorShop.Entities\MonitorShop.Entities.csproj" />
  </ItemGroup>

</Project>
